version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-producer
    depends_on:
      - kafka
    entrypoint: >
      /bin/bash -c "
      echo 'Producing messages to Kafka topic...';
      echo -e 'Hello, Kafka from Docker!' | kafka-console-producer --broker-list kafka:9092 --topic test-topic;
      sleep infinity
      "
    environment:
      KAFKA_BROKER: kafka:9092
  consumer:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-consumer
    depends_on:
      - kafka
    entrypoint: >
      /bin/bash -c "
      echo 'Consuming messages from Kafka topic...';
      kafka-console-consumer --bootstrap-server kafka:9092 --topic test-topic --from-beginning;
      sleep infinity
      "
    environment:
      KAFKA_BROKER: kafka:9092
