spring:
  application:
    name: hhplus-concert-reservation

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: hhp.concert.reservation
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    defaultModelsExpandDepth: -1