spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:concertdb
    username: sa
  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      continue-on-error: true
#      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: hhp.concert.reservation
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    defaultModelsExpandDepth: -1